export default {
  appKey: "vtexappkey-medbeauty-HVDKJP",
  appToken: "JUCYTUXVYSNJAEKXEOFUQHFOQZGHEUYXGPWNQQYPQJVCAGSFZVMYMVKBPNITOPRDTQCLIXGNQPDHMDNJGAIIIAKLEUXCIEBBRRJJEGXCPYHXSCPLZZMNGJUTFRHNZEFL"
}